name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t whitefly-fastapi .

    - name: Log in to GitHub Container Registry
      run: |
        echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Push Docker image to GHCR
      run: |
        docker tag whitefly-fastapi:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/whitefly-fastapi:latest
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/whitefly-fastapi:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: <your_azure_web_app_name>
        images: ghcr.io/${{ secrets.GHCR_USERNAME }}/whitefly-fastapi:latest
        publish-profile: ${{ secrets.AZURE_WEBAPPS_PUBLISH_PROFILE }}

